version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.sourceforge.plantuml:plantuml
    versions:
    - 1.2021.0
    - 1.2021.1
    - 1.2021.2
    - 1.2021.3
    - 1.2021.4
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.sun.xml.bind:jaxb-impl
    versions:
    - 3.0.0
  - dependency-name: com.vladmihalcea:hibernate-types-52
    versions:
    - 2.10.2
    - 2.10.3
  - dependency-name: org.openapitools:openapi-generator-maven-plugin
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: com.aliyun.oss:aliyun-sdk-oss
    versions:
    - 3.11.2
    - 3.11.3
  - dependency-name: cn.hutool:hutool-http
    versions:
    - 5.5.7
    - 5.5.8
  - dependency-name: cn.hutool:hutool-dfa
    versions:
    - 5.5.7
    - 5.5.8
  - dependency-name: cn.hutool:hutool-core
    versions:
    - 5.5.7
    - 5.5.8
