== 授权接口

基于 JWT 的接口认证。

=== 获取 TOKEN
==== 正常
operation::AuthorizationAPITest--is-token-created[snippets='http-request,request-headers,request-parameters,response-fields,http-response']

==== 异常：缺少参数
operation::AuthorizationAPITest--is-token-created-error-parameter[snippets='http-response']

==== 异常：用户不存在
operation::AuthorizationAPITest--is-token-created-error-username[snippets='http-response']

==== 异常：密码错误
operation::AuthorizationAPITest--is-token-created-error-password[snippets='http-response']


=== 刷新 TOKEN
==== 正常
operation::AuthorizationAPITest--is-token-refreshed[snippets='http-request,request-headers,request-parameters,response-fields,http-response']

=== 访问 ENDPOINT
==== 状态码 200
operation::AuthorizationAPITest--is-endpoint-ok[snippets='curl-request,http-response']

==== 状态码 401
operation::AuthorizationAPITest--is-endpoint-unauthorized[snippets='curl-request,http-response']

==== 状态码 403
operation::AuthorizationAPITest--is-endpoint-forbidden[snippets='curl-request,http-response']

=== 访问 REST DATA
==== 状态码 200
operation::AuthorizationAPITest--is-rest-data-ok[snippets='curl-request,http-response']

==== 状态码 401
operation::AuthorizationAPITest--is-rest-data-unauthorized[snippets='curl-request,http-response']

==== 状态码 403
operation::AuthorizationAPITest--is-rest-data-forbidden[snippets='curl-request,http-response']